import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import QueryProvider from "./queryprovider";
import SessionWrapper from "./sessionwrapper";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { AuthProvider } from "@/contexts/AuthContext";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions); // get session
  return (
    <html lang="en" className={montserrat.variable}>
      <body>
        <AuthProvider>
          <SessionWrapper session={session}>
            <QueryProvider>{children}</QueryProvider>
          </SessionWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
